keys:
  - &larsg age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy
  - &github_actions age16taq0yzdqufupmpy300afw44kz503q7t7un9xyd0sdl62l3lvcasxfn455

creation_rules:
  # Project administration
  - path_regex: ^project/secrets.yaml$
    key_groups:
      - age:
          - *larsg
          - *github_actions
  # larsgunnar.no domain administration
  - path_regex: ^domains/larsgunnar.no/secrets.yaml$
    key_groups:
      - age:
          - *larsg
          - *github_actions
  # kodehode.larsgunnar.no domain administration
  - path_regex: ^domains/kodehode.larsgunnar.no/secrets.yaml$
    key_groups:
      - age:
          - *larsg
          - *github_actions
  # Test infrastructure
  - path_regex: ^test-infra/.*/secrets.yaml$
    key_groups:
      - age:
          - *larsg
          - *github_actions
