keys:
  - &larsg age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy

creation_rules:
  # Project administration
  - path_regex: ^project/secrets.yaml$
    key_groups:
      - age:
          - *larsg
  # larsgunnar.no domain administration
  - path_regex: ^domains/larsgunnar.no/secrets.yaml$
    key_groups:
      - age:
          - *larsg
  # kodehode.larsgunnar.no domain administration
  - path_regex: ^domains/kodehode.larsgunnar.no/secrets.yaml$
    key_groups:
      - age:
          - *larsg
