TF_VAR_cloudflare_token: ENC[AES256_GCM,data:ILmOzoYj0E0GF7tkDD8KjvsM4WI8RoJghc4NLVznH7fYlCA1YNY71A==,iv:iohLiAy9WX4p1CmvZ7r0MXcIVD8NcIVLMYjE6xjv0zw=,tag:jtO3Zynv7eQ02aUoKa1c2A==,type:str]
TF_VAR_cloudflare_account_id: ENC[AES256_GCM,data:NNSvB6b+1KRif0hJj7lKidfBB1IOvcZMfDSnXY7+vZo=,iv:J1nS/Jr0E8RwniK+D4Q9X/aEssS6gIuLo461j20jVxI=,tag:5tr/Eq7L+47AEg/ty/XmUw==,type:str]
sops:
  age:
    - recipient: age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhTThXakU4bHN0dXhUUitv
        aXBNaVJDTmtWZmdybXF6bmdlcG9MZm5xeVdVCjI0c0dvUGJ0RkVDbnQydE1hK1NO
        aEk1bkR0dlNkYkNqak1iQ2tRMXhFNUUKLS0tIG5OZUJjLzBiSVZxcWk1dHZ4ZkZ6
        QVpna3oxdDJtZURBdGxPUTdQN1hGSTgKT6IkRx7AMHnkwhBWzCyRuiqSxXWbjDeT
        ZZwP644zMDWvSvwy8FJu58tiZplWdpEoQ9LjPM/3SI9Aai4f1gI/6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-07T16:54:33Z"
  mac: ENC[AES256_GCM,data:o1eKQmDTv5hI7xDFX7fbLKI40X5/qMdmovvkB3rVBP8iilbOi2stXM28NhBVzTUnHIPUQxbNKcicSXnVyGmMDWJ5cMLIOUfLBTmckVLj9WlUE6wR1nvSXNrLJ63NvFeEDxlEeC/Ck0mO4/49KLUTBXafLjVsKk/OSKToX2epnnE=,iv:aeveJ0HFJQLVOeIOcm3FagVQkpe3EPXqDD/g0eFszGo=,tag:Mp1Ta2lU5wJsrCu0ZOat8A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
