name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  check-hcl-formatting:
    name: Check HCL Formatting in ${{ matrix.directory }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory:
          - domains/larsgunnar.no
          - domains/kodehode.larsgunnar.no
          - project
          - test-infra/server
          - test-infra/web-app

    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          nix develop --command bash -c "
          echo 'Checking HCL formatting in ${{ matrix.directory }}...'
          cd ${{ matrix.directory }}
          tofu fmt -check -recursive .
          "
