name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  iac-format-check:
    name: IaC Format Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix develop --command just iac-format-check

  iac-validate:
    name: IaC Validate
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix develop --command just iac-init
      - run: nix develop --command just iac-validate

  ci-summary:
    name: CI Summary
    runs-on: ubuntu-latest
    needs: [iac-format-check, iac-validate]
    if: always()

    steps:
      - name: Check CI results
        run: |
          # Handle cases where dependency jobs were skipped or didn't run
          format_result="${{ needs.iac-format-check.result }}"
          validate_result="${{ needs.iac-validate.result }}"

          echo "Format check result: ${format_result:-'skipped'}"
          echo "Validate check result: ${validate_result:-'skipped'}"

          # If both jobs were skipped (e.g., no IaC changes), consider it a pass
          if [ "${format_result}" == "skipped" ] && [ "${validate_result}" == "skipped" ]; then
            echo "✅ No IaC changes detected - CI Summary passes"
            exit 0
          fi

          # If either job failed, fail the summary
          if [ "${format_result}" == "failure" ] || [ "${validate_result}" == "failure" ]; then
            echo "❌ CI checks failed"
            echo "Format check: ${format_result:-'skipped'}"
            echo "Validate check: ${validate_result:-'skipped'}"
            exit 1
          fi

          # If we reach here, all required jobs passed
          echo "✅ All CI checks passed"
          exit 0
