name: Labeler

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: srvaroa/labeler@1
        with:
          config_path: .github/labeler-rules.yaml
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
