provider_block_unencrypted: |
  ====================
  Provider Credentials
  ====================
TF_VAR_cloudflare_token: ENC[AES256_GCM,data:9Gc7L4dR9o4IlIKf3+xP44Q3GvZ4B+f7kljOioD3rMN9QdwW9dHKCw==,iv:ZFPFol5HzNsFVk1gyzdU9ZXz4PdA0vn/HVNRdwsORLc=,tag:tLXoOeaBXdtW7+WOKzZj1w==,type:str]
TF_VAR_cloudflare_account_id: ENC[AES256_GCM,data:fqA=,iv:eud3ybsnpForhQEYq/biZKPJ1wGJuSmzryB1jB7Lz/k=,tag:grG1Umb9GqEhNbluS6l56Q==,type:str]
TF_VAR_zone_id: ENC[AES256_GCM,data:7+s=,iv:gS9ef4Owy1W8UQzlRilWnR6HTyLp51fNVC4nyBFGZH8=,tag:SkLsangeL+TmtZgLB5m80w==,type:str]
backend_block_unencrypted: |
  ==============================
  OpenTofu Backend Configuration
  ==============================
AWS_DEFAULT_REGION: ENC[AES256_GCM,data:EyTFfQ==,iv:Zb/pT2W9ueLQP4DRsXbu8iM0gFM6JaEzm77nDHa5Iqg=,tag:atopB8YchzGSzR9aOytAEw==,type:str]
AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:aCU/9lWBENMSwKwb3PwNFzHrbbs=,iv:1FAgW3yz6F30er1+RAHMaGUkSj7e4VulOET+nyUe9j4=,tag:JGZwEn4lWVt5XIGBxfezRQ==,type:str]
AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:4/hj6MCNMjtR1ZG2Gr8v9lCh9mAYAodALklUYVjkshbRev2N16sgGw==,iv:wBsSAAjGDXFIwFcuyOjxLfcCj5RzkjxL0wEK6xHYxzI=,tag:hrRo3eQxSgrIT0BZrfDXDQ==,type:str]
AWS_ENDPOINT_URL_S3: ENC[AES256_GCM,data:H9S4pFUn9Wqp8OI/IwgRwmwRyB1tk4cfUbu3FhAvgJIvyQk=,iv:R4srRBTc7aXqVBBo++3J7IVn+6dAlctu/kJiY9jB7Gw=,tag:jufvpBYC226iDQd7IOcwRQ==,type:str]
sops:
  age:
    - recipient: age1w7stgltn2stl94ap045qrzufmy9x9wuqnzrlug60v58g5j8m6c3qym8uxy
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtalh0Rnh1QngzTDFPTnc1
        V1JCRVJIOG1oc2dEY0s4QmNpdmwwQlBKZDJ3CmdNYkhkQ2Q3ZVh2UjBrNWJPOVlr
        Z21TSUgxSDJWamtUT2NFNzVocld4aXcKLS0tIDhzTEdyZjN0aDNhdzcvdGJLY3lW
        cUZNVFViN0pkaUJzMWtvL0NBT0FzS00KEyIOGK4IdieGdzCUEKx/b+xz0RcitRpk
        E9mg64en0P4gcacAO9eBcbj/hpsFdqLgOGT+EC1S7dBsbWTMni4uxQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-10-08T00:46:39Z"
  mac: ENC[AES256_GCM,data:GzaIrGzmZ0wzI6Jb4ivEJI/zWqzZ2O853eeLBDWoAdYCysQrm4+RpzTx4VltwbvCjff6C4iBY0MkgKLc8/LTeszz8xC3pFkqjtQOvaF6bW3af6z3+PbYUguiNfEBif9wHuRx8iujHCSJWPF48YHZ706U5k/YD+o80sIPfbiQtg8=,iv:ve4sAYF+2Y+xS+gXluDoQS7u1zmWQ5Y0q99Q53NEmes=,tag:yeGXl4qNdD0jXXYKRWiASA==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.10.2
